-- Write your SQL code here
CREATE TABLE TRANSACTION_HISTORY (
    HistoryId INT AUTO_INCREMENT PRIMARY KEY,
    TransactionId INT NOT NULL,
    OldAmount DECIMAL(15, 2),
    NewAmount DECIMAL(15, 2),
    ChangeDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TransactionId) REFERENCES TRANSACTION(TransactionId)
) ENGINE=InnoDB;

CREATE TRIGGER TRG_AFTER_UPDATE_ON_TRANSACTION
AFTER UPDATE ON TRANSACTION
FOR EACH ROW
INSERT INTO TRANSACTION_HISTORY (TransactionId, OldAmount, NewAmount)
VALUES (OLD.TransactionId, OLD.Amount, NEW.Amount);
