-- Write your SQL code here
 CREATE TABLE EMPLOYEE_ARCHIVE (
    ArchiveId INT AUTO_INCREMENT PRIMARY KEY,
    EmployeeId INT NOT NULL,
    Name VARCHAR(100),
    Position VARCHAR(50),
    ArchiveDate DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TRIGGER TRG_BEFORE_DELETE_ON_EMPLOYEE
BEFORE DELETE ON EMPLOYEE
FOR EACH ROW
INSERT INTO EMPLOYEE_ARCHIVE (EmployeeId, Name, Position)
VALUES (OLD.EmployeeId, OLD.Name, OLD.Position);